name: Daily Forecast
on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yfinance torch transformers pandas einops huggingface_hub safetensors requests
      - name: Run daily analysis and send email
        env:
          GMAIL_ADRESS: ${{ secrets.GMAIL_ADRESS }}
          BREVO_API: ${{ secrets.BREVO_API }}
        run: python send_email.py
